### ISSUE TITLE
Issue on CMD after py blogen.py or python blogen.py

### ISSUE THREAD

**Issue by z3rotto** [AJaySi/AI-Blog-Writer#2]
E:\CHATGPT-AI-Marketing-Tools-CMD\AI-Blog-Writer>py blogen.py
Traceback (most recent call last):
  File "E:\CHATGPT-AI-Marketing-Tools-CMD\AI-Blog-Writer\blogen.py", line 6, in <module>
    from PyInquirer import prompt
  File "D:\Users\vaan1\AppData\Local\Programs\Python\Python312\Lib\site-packages\PyInquirer\__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "D:\Users\vaan1\AppData\Local\Programs\Python\Python312\Lib\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "D:\Users\vaan1\AppData\Local\Programs\Python\Python312\Lib\site-packages\prompt_toolkit\interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "D:\Users\vaan1\AppData\Local\Programs\Python\Python312\Lib\site-packages\prompt_toolkit\application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "D:\Users\vaan1\AppData\Local\Programs\Python\Python312\Lib\site-packages\prompt_toolkit\key_binding\bindings\basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "D:\Users\vaan1\AppData\Local\Programs\Python\Python312\Lib\site-packages\prompt_toolkit\renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "D:\Users\vaan1\AppData\Local\Programs\Python\Python312\Lib\site-packages\prompt_toolkit\styles\__init__.py", line 8, in <module>
    from .from_dict import *
  File "D:\Users\vaan1\AppData\Local\Programs\Python\Python312\Lib\site-packages\prompt_toolkit\styles\from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (D:\Users\vaan1\AppData\Local\Programs\Python\Python312\Lib\collections\__init__.py)

E:\CHATGPT-AI-Marketing-Tools-CMD\AI-Blog-Writer>pip blogen.py
ERROR: unknown command "blogen.py"

I have this issue and I don't see the file .env.
What should I do?

Thank you for your help

**Comment by AJaySi** [comment]
Hello,

1). I pushed a new patch, please use that. I also updated the README
2). The tool 'alwrity' is interactive will guide you through setup on commandline.
3). The errors are because the required modules are missing.
Try on the prompt: pip install -r requirements.

4). Damn Windows, I have tested my code on linux. But, give me 3-4 days and I will sort out issues for Windows. Its TBD.
Regards.

**Comment by AJaySi** [comment]
Please let me know your usecase or how you will use this tool ?
I will then get those features ironed out on priority. Thanks.

**Comment by AJaySi** [comment]
I have updated the README with repl.it option 2. This will help get started quicker on cloud.

**Comment by AJaySi** [comment]
Try the latest code, I have tested on windows.
